"""Generate, compile, validate, and register a MUGEN X stage."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parents[1]
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from asset_gen import sd_client
from common.asset_compile import compile_sff, discover_sprmake2
from common.paths import repo_path
from common.roster_registration import register_stage


def slugify(name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_-]+", "_", name.strip()).strip("_")
    if not slug:
        raise ValueError("Stage name must contain at least one letter or number")
    return slug


def generate_background(path: Path, name: str, prompt: str, width: int, height: int) -> None:
    if not sd_client.check_connection():
        raise ConnectionError(
            "Stable Diffusion API is unavailable. Start Automatic1111 with --api or provide --source-image."
        )
    full_prompt = (
        f"{name}, original 2D fighting game stage, {prompt}, wide environmental background, "
        "clear flat fighting floor across the lower portion, no characters, no text, no UI, cinematic depth"
    )
    negative = "characters, people, text, logo, watermark, interface, close-up object"
    result = sd_client.generate_image(
        full_prompt,
        negative_prompt=negative,
        width=width,
        height=height,
        steps=24,
        output_path=str(path),
    )
    if result is None or not path.is_file():
        raise RuntimeError("Stage background generation failed")


def write_stage_def(path: Path, name: str, slug: str, width: int, height: int) -> None:
    floor_y = int(height * 0.88)
    bound = max(220, width // 3)
    text = f"""; Generated by MUGEN X
[Info]
name = "{name}"
displayname = "{name}"
versiondate = 09,02,2026
mugenversion = 1.1
author = "MUGEN X ENGINE"

[Camera]
startx = 0
starty = 0
boundleft = -{bound}
boundright = {bound}
boundhigh = -120
boundlow = 0
verticalfollow = .2
floortension = 40
tension = 60

[PlayerInfo]
p1startx = -90
p1starty = 0
p1facing = 1
p2startx = 90
p2starty = 0
p2facing = -1
leftbound = -1200
rightbound = 1200
topbound = 0
botbound = 0

[Bound]
screenleft = 25
screenright = 25

[StageInfo]
zoffset = {floor_y}
autoturn = 1
resetBG = 1
localcoord = {width},{height}
xscale = 1
yscale = 1

[Shadow]
intensity = 120
color = 0,0,0
yscale = .25
fade.range = -100,80

[Reflection]
intensity = 0

[Music]
bgmusic =
bgmvolume = 100

[BGdef]
spr = {slug}.sff
debugbg = 0

[BG Main]
type = normal
spriteno = 0,0
layerno = 0
start = 0,0
delta = 1,1
trans = none
mask = 0
tile = 0,0
"""
    path.write_text(text, encoding="utf-8")


def validate_stage(def_path: Path, sff_path: Path) -> list[str]:
    failures: list[str] = []
    if not def_path.is_file():
        failures.append("stage DEF was not created")
    if not sff_path.is_file():
        failures.append("stage SFF was not created")
    if def_path.is_file():
        text = def_path.read_text(encoding="utf-8", errors="ignore")
        if f"spr = {sff_path.name}" not in text:
            failures.append("BGdef does not reference the compiled SFF")
        if "[BG Main]" not in text or "spriteno = 0,0" not in text:
            failures.append("stage background definition is incomplete")
    return failures


def build_stage(args: argparse.Namespace) -> dict:
    slug = slugify(args.name)
    directory = repo_path("stages", "generated", slug)
    if directory.exists() and not args.overwrite:
        raise FileExistsError(f"Stage directory already exists: {directory}. Use --overwrite to replace generated files.")
    directory.mkdir(parents=True, exist_ok=True)

    source_png = directory / "0-0.png"
    if args.source_image:
        src = Path(args.source_image).expanduser().resolve()
        if not src.is_file():
            raise FileNotFoundError(src)
        shutil.copy2(src, source_png)
    elif not args.no_image:
        generate_background(source_png, args.name, args.prompt, args.width, args.height)

    compiled = False
    compile_error = None
    sff_path = directory / f"{slug}.sff"
    try:
        compile_sff(directory, sff_path.name, axis_mode="origin")
        compiled = True
    except Exception as exc:
        compile_error = str(exc)
        if not args.allow_uncompiled:
            raise

    def_path = directory / f"{slug}.def"
    write_stage_def(def_path, args.name, slug, args.width, args.height)
    failures = validate_stage(def_path, sff_path) if compiled else ["stage SFF is not compiled"]

    registered = False
    if args.register and compiled and not failures:
        registered = register_stage(f"stages/generated/{slug}/{slug}.def")
    elif args.register and (not compiled or failures):
        raise RuntimeError(
            "Generated stage was not registered because it is not release-valid: " + "; ".join(failures)
        )

    return {
        "name": args.name,
        "slug": slug,
        "directory": str(directory),
        "def": str(def_path),
        "sff": str(sff_path) if compiled else None,
        "compiled": compiled,
        "compiler": str(discover_sprmake2()) if discover_sprmake2() else None,
        "compile_error": compile_error,
        "validation_failures": failures,
        "registered": registered,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name")
    parser.add_argument("--prompt", default="memorable arena with strong foreground and background separation")
    parser.add_argument("--source-image", help="Use an existing PNG instead of Stable Diffusion")
    parser.add_argument("--no-image", action="store_true", help="Use an already-present 0-0.png")
    parser.add_argument("--width", type=int, default=1280)
    parser.add_argument("--height", type=int, default=720)
    parser.add_argument("--allow-uncompiled", action="store_true", help="Keep scaffold if sprmake2 is unavailable; never auto-register it")
    parser.add_argument("--no-register", dest="register", action="store_false")
    parser.add_argument("--overwrite", action="store_true")
    parser.set_defaults(register=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.width < 320 or args.height < 240:
        print("MUGEN X stage generation failed: minimum localcoord is 320x240", file=sys.stderr)
        return 1
    try:
        result = build_stage(args)
    except Exception as exc:
        print(f"MUGEN X stage generation failed: {exc}", file=sys.stderr)
        return 1

    print("MUGEN X STAGE GENERATION COMPLETE")
    for key, value in result.items():
        print(f"{key}: {value}")
    return 0 if result["compiled"] and not result["validation_failures"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
