[command]
name="CPU1"
command=U,D,F,F,B,B
time=1
[command]
name="CPU2"
command=U,D,F,F,B,F
time=1
[command]
name="CPU3"
command=U,D,F,F,B,D
time=1
[command]
name="CPU4"
command=U,D,F,F,B,U
time=1
[command]
name="CPU5"
command=U,D,F,F,U,B
time=1
[command]
name="CPU6"
command=U,D,F,F,D,B
time=1
[command]
name="CPU7"
command=U,D,F,F,F,B
time=1
[command]
name="CPU8"
command=U,D,U,F,B,B
time=1
[command]
name="CPU9"
command=U,D,D,F,B,B
time=1
[command]
name="CPU10"
command=D,D,F,F,B,B
time=1
[command]
name="CPU11"
command=U,U,F,F,B,B
time=1
[command]
name="CPU12"
command=U,B,F,F,B,B
time=1
[command]
name="CPU13"
command=D,U,B,B,B,U,D
time=1
[command]
name="CPU14"
command=D,U,B,B,B,U,U
time=1
[command]
name="CPU15"
command=D,U,B,B,B,U,B
time=1
[command]
name="CPU16"
command=D,U,B,B,B,U,F
time=1
[command]
name="CPU17"
command=D,U,B,B,B,D,D
time=1
[command]
name="CPU18"
command=D,U,B,B,B,B,D
time=1
[command]
name="CPU19"
command=D,U,B,B,B,F,D
time=1
[command]
name="CPU20"
command=D,U,B,B,F,U,D
time=1
[command]
name="CPU21"
command=D,U,B,B,U,U,D
time=1
[command]
name="CPU22"
command=D,U,B,B,D,U,D
time=1
[command]
name="CPU23"
command=D,U,B,F,B,U,D
time=1
[command]
name="CPU24"
command=D,U,B,U,B,U,D
time=1
[command]
name="CPU25"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU26"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU27"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU28"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU29"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU30"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU31"
command=U,U,B,U,B,U,D
time=1
[command]
name="CPU32"
command=U,U,B,U,B,U,D
time=1

[command]
name="FCcba"
command=$U,$F,$D,$B,a
time=30
[command]
name="FCcba"
command=$F,$D,$B,$U,a
time=30
[command]
name="FCcba"
command=$U,$B,$D,$F,a
time=30
[command]
name="FCcba"
command=$B,$D,$F,$U,a
time=30
[command]
name="FCcba"
command=$U,$F,$D,$B,b
time=30
[command]
name="FCcba"
command=$F,$D,$B,$U,b
time=30
[command]
name="FCcba"
command=$U,$B,$D,$F,b
time=30
[command]
name="FCcba"
command=$B,$D,$F,$U,b
time=30
[command]
name="FCcba"
command=$U,$F,$D,$B,c
time=30
[command]
name="FCcba"
command=$F,$D,$B,$U,c
time=30
[command]
name="FCcba"
command=$U,$B,$D,$F,c
time=30
[command]
name="FCcba"
command=$B,$D,$F,$U,c
time=30

[command]
name="FCzyx"
command=$U,$F,$D,$B,x
time=30
[command]
name="FCzyx"
command=$F,$D,$B,$U,x
time=30
[command]
name="FCzyx"
command=$U,$B,$D,$F,x
time=30
[command]
name="FCzyx"
command=$B,$D,$F,$U,x
time=30
[command]
name="FCzyx"
command=$U,$F,$D,$B,y
time=30
[command]
name="FCzyx"
command=$F,$D,$B,$U,y
time=30
[command]
name="FCzyx"
command=$U,$B,$D,$F,y
time=30
[command]
name="FCzyx"
command=$B,$D,$F,$U,y
time=30
[command]
name="FCzyx"
command=$U,$F,$D,$B,z
time=30
[command]
name="FCzyx"
command=$F,$D,$B,$U,z
time=30
[command]
name="FCzyx"
command=$U,$B,$D,$F,z
time=30
[command]
name="FCzyx"
command=$B,$D,$F,$U,z
time=30

[command]
name="D~Uabc"
command=~30$D,U,a+b
[command]
name="D~Uabc"
command=~30$D,U,a+c
[command]
name="D~Uabc"
command=~30$D,U,b+c

[command]
name="D~Uxyz"
command=~30$D,U,x+y
[command]
name="D~Uxyz"
command=~30$D,U,x+z
[command]
name="D~Uxyz"
command=~30$D,U,y+z

[command]
name="B~Fabc"
command=~30$B,F,a+b
[command]
name="B~Fabc"
command=~30$B,F,a+c
[command]
name="B~Fabc"
command=~30$B,F,b+c

[command]
name="B~Fxyz"
command=~30$B,F,x+y
[command]
name="B~Fxyz"
command=~30$B,F,x+z
[command]
name="B~Fxyz"
command=~30$B,F,y+z

[command]
name="QCBabc"
command=~D,DB,B,a+b
[command]
name="QCBabc"
command=~D,DB,B,a+c
[command]
name="QCBabc"
command=~D,DB,B,b+c

[command]
name="QCBxyz"
command=~D,DB,B,x+y
[command]
name="QCBxyz"
command=~D,DB,B,x+z
[command]
name="QCBxyz"
command=~D,DB,B,y+z

[command]
name="B~Fa"
command=~30$B,F,a
[command]
name="B~Fb"
command=~30$B,F,b
[command]
name="B~Fc"
command=~30$B,F,c

[command]
name="B~Fx"
command=~30$B,F,x
[command]
name="B~Fy"
command=~30$B,F,y
[command]
name="B~Fz"
command=~30$B,F,z

[command]
name="QCBa"
command=~D,DB,B,a
[command]
name="QCBb"
command=~D,DB,B,b
[command]
name="QCBc"
command=~D,DB,B,c

[command]
name="QCBx"
command=~D,DB,B,x
[command]
name="QCBy"
command=~D,DB,B,y
[command]
name="QCBz"
command=~D,DB,B,z

[command]
name="abc"
command=a+b
time=1
[command]
name="abc"
command=a+c
time=1
[command]
name="abc"
command=b+c
time=1
[command]
name="xyz"
command=x+y
time=1
[command]
name="xyz"
command=x+z
time=1
[command]
name="xyz"
command=y+z
time=1

[command]
name="holda"
command=/$a
[command]
name="holdb"
command=/$b
[command]
name="holdc"
command=/$c
[command]
name="holdx"
command=/$x
[command]
name="holdy"
command=/$y
[command]
name="holdz"
command=/$z

[command]
name="recovery"
command=a
time=1
[command]
name="recovery"
command=b
time=1
[command]
name="recovery"
command=c
time=1
[command]
name="recovery"
command=x
time=1
[command]
name="recovery"
command=y
time=1
[command]
name="recovery"
command=z
time=1
[command]
name="FF"
command=F,F
[command]
name="BB"
command=B,B
[command]
name="a"
command=a
time=1
[command]
name="b"
command=b
time=1
[command]
name="c"
command=c
time=1
[command]
name="x"
command=x
time=1
[command]
name="y"
command=y
time=1
[command]
name="z"
command=z
time=1
[command]
name="start"
command=s
time=1
[command]
name="holdfwd"
command=/$F
[command]
name="holdback"
command=/$B
[command]
name="holdup" 
command=/$U
[command]
name="holddown"
command=/$D

[statedef -1]

[state -1,thunder break]
type=changestate
value=3700
triggerall=((command="D~Uabc")&&!var(10))||((var(9)<100)&&(p2dist x>120)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=power>999
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=40)
trigger2=movehit&&(stateno=[200,599])
[state -1,mega stake]
type=changestate
value=3600
triggerall=((command="D~Uxyz")&&!var(10))||((var(9)<200)&&(p2dist x>120)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=power>999
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=40)
trigger2=movehit&&(stateno=[200,599])
[state -1,hop kick]
type=changestate
value=3300
triggerall=((command="B~Fabc")&&!var(10))||((var(9)<200)&&(p2dist x=[80,120])&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=power>999
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,giga brood]
type=changestate
value=3200
triggerall=((command="B~Fxyz")&&!var(10))||((var(9)<300)&&(p2dist x>120)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=power>999
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,hyper giga burn]
type=changestate
value=3100
triggerall=((command="QCBabc")&&!var(10))||((var(9)<600)&&(p2dist x<40)&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=power>999
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,hyper gyro crush]
type=changestate
value=3000
triggerall=((command="QCBxyz")&&!var(10))||((var(9)<200)&&(p2dist x=[40,80])&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=power>999
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,hyper pounce]
type=changestate
value=4900
triggerall=p2stateno=[5100,5110]
triggerall=(statetype=s)||(statetype=c)
triggerall=power>999
trigger1=((command="abc")||(command="xyz"))&&(stateno=40)&&!var(10)
trigger2=ctrl&&var(10)&&(random<50)

[state -1,mega spike]
type=changestate
value=1500
triggerall=((command="FCcba")&&!var(10))||((var(9)<125)&&(p2dist x<20)&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=40)
[state -1,graviton knuckle]
type=changestate
value=1400
triggerall=((command="FCzyx")&&!var(10))||((var(9)<250)&&(p2dist x<20)&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=40)

[state -1,giga buster (1)]
type=changestate
value=1300
triggerall=((command="B~Fa")&&!var(10))||((var(9)<50)&&(p2dist x>110)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,giga buster (2)]
type=changestate
value=1310
triggerall=((command="B~Fb")&&!var(10))||((var(9)<100)&&(p2dist x>130)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,giga buster (3)]
type=changestate
value=1320
triggerall=((command="B~Fc")&&!var(10))||((var(9)<150)&&(p2dist x>150)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])

[state -1,mega forehead (1)]
type=changestate
value=1200
triggerall=((command="B~Fx")&&!var(10))||((var(9)<100)&&(p2dist x>110)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,mega forehead (2)]
type=changestate
value=1210
triggerall=((command="B~Fy")&&!var(10))||((var(9)<200)&&(p2dist x>130)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,mega forehead (3)]
type=changestate
value=1220
triggerall=((command="B~Fz")&&!var(10))||((var(9)<300)&&(p2dist x>150)&&var(10)&&(p2movetype!=a)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])

[state -1,giga burn (1)]
type=changestate
value=1100
triggerall=((command="QCBa")&&!var(10))||((var(9)<150)&&(p2dist x<40)&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,giga burn (2)]
type=changestate
value=1110
triggerall=((command="QCBb")&&!var(10))||((var(9)<300)&&(p2dist x<50)&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,giga burn (3)]
type=changestate
value=1120
triggerall=((command="QCBc")&&!var(10))||((var(9)<450)&&(p2dist x<60)&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])

[state -1,gyro crush (1)]
type=changestate
value=1000
triggerall=((command="QCBx")&&!var(10))||((var(9)<50)&&(p2dist x=[50,110])&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,gyro crush (2)]
type=changestate
value=1010
triggerall=((command="QCBy")&&!var(10))||((var(9)<100)&&(p2dist x=[50,130])&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])
[state -1,gyro crush (3)]
type=changestate
value=1020
triggerall=((command="QCBz")&&!var(10))||((var(9)<150)&&(p2dist x=[50,150])&&var(10)&&(p2stateno!=[5100,5199]))
triggerall=(statetype=s)||(statetype=c)
trigger1=ctrl||(stateno=[100,109])
trigger2=movehit&&(stateno=[200,599])

[state -1,pounce]
type=changestate
value=2900
triggerall=p2stateno=[5100,5110]
triggerall=(statetype=s)||(statetype=c)
trigger1=(command="recovery")&&(stateno=40)&&!var(10)
trigger2=ctrl&&var(10)&&(random<50)

[state -1,chin basher]
type=changestate
value=800
triggerall=ctrl&&(statetype=s)
trigger1=p2bodydist x<20
trigger1=p2dist x>0
trigger1=p2statetype!=a
trigger1=p2stateno!=[5000,5199]
trigger1=(!var(10)&&(stateno=20)&&(command="y"))||(var(10)&&(random<250))
[state -1,two-handed squeeze]
type=changestate
value=810
triggerall=ctrl&&(statetype=s)
trigger1=p2bodydist x<20
trigger1=p2dist x>0
trigger1=p2statetype!=a
trigger1=p2stateno!=[5000,5199]
trigger1=(!var(10)&&(stateno=20)&&(command="z"))||(var(10)&&(random<500))
[state -1,bottom grip]
type=changestate
value=820
triggerall=ctrl&&(statetype=s)
trigger1=p2bodydist x<20
trigger1=p2dist x>0
trigger1=p2statetype!=a
trigger1=p2stateno!=[5000,5199]
trigger1=(!var(10)&&(stateno=20)&&(command="b"))||(var(10)&&(random<750))
[state -1,mega shock]
type=changestate
value=830
triggerall=ctrl&&(statetype=s)
trigger1=p2bodydist x<20
trigger1=p2dist x>0
trigger1=p2statetype!=a
trigger1=p2stateno!=[5000,5199]
trigger1=(!var(10)&&(stateno=20)&&(command="c"))||var(10)

[state -1,air light punch]
type=changestate
value=600
triggerall=((command="x")&&!var(10))||((random<500)&&(p2dist x<30)&&var(10))
triggerall=statetype=a
trigger1=ctrl
[state -1,air medium punch]
type=changestate
value=610
triggerall=((command="y")&&!var(10))||((random<500)&&(p2dist x<50)&&var(10))
triggerall=statetype=a
trigger1=ctrl
trigger2=movehit
trigger2=stateno=600
[state -1,air hard punch]
type=changestate
value=620
triggerall=((command="z")&&!var(10))||((random<500)&&(p2dist x<70)&&var(10))
triggerall=statetype=a
trigger1=ctrl
trigger2=movehit
trigger2=(stateno=600)||(stateno=610)
[state -1,air light kick]
type=changestate
value=630
triggerall=((command="a")&&!var(10))||((p2dist x<30)&&var(10))
triggerall=statetype=a
trigger1=ctrl
[state -1,air medium kick]
type=changestate
value=640
triggerall=((command="b")&&!var(10))||((p2dist x<50)&&var(10))
triggerall=statetype=a
trigger1=ctrl
trigger2=movehit
trigger2=stateno=630
[state -1,air hard kick]
type=changestate
value=650
triggerall=((command="c")&&!var(10))||((p2dist x<70)&&var(10))
triggerall=statetype=a
trigger1=ctrl
trigger2=movehit
trigger2=(stateno=630)||(stateno=640)

[state -1,crouch light punch]
type=changestate
value=400
triggerall=((command="x")&&!var(10))||((random<500)&&(p2dist x<30)&&var(10))
triggerall=statetype=c
trigger1=ctrl
[state -1,crouch medium punch]
type=changestate
value=410
triggerall=((command="y")&&!var(10))||((random<500)&&(p2dist x<50)&&var(10))
triggerall=statetype=c
trigger1=ctrl
trigger2=movehit
trigger2=stateno=400
[state -1,crouch hard punch]
type=changestate
value=420
triggerall=((command="z")&&!var(10))||((random<500)&&(p2dist x<70)&&var(10))
triggerall=statetype=c
trigger1=ctrl
trigger2=movehit
trigger2=(stateno=400)||(stateno=410)
[state -1,crouch light kick]
type=changestate
value=430
triggerall=((command="a")&&!var(10))||((p2dist x<30)&&var(10))
triggerall=statetype=c
trigger1=ctrl
[state -1,crouch medium kick]
type=changestate
value=440
triggerall=((command="b")&&!var(10))||((p2dist x<50)&&var(10))
triggerall=statetype=c
trigger1=ctrl
trigger2=movehit
trigger2=stateno=430
[state -1,crouch hard kick]
type=changestate
value=450
triggerall=((command="c")&&!var(10))||((p2dist x<70)&&var(10))
triggerall=statetype=c
trigger1=ctrl
trigger2=movehit
trigger2=(stateno=430)||(stateno=440)

[state -1,stand light punch]
type=changestate
value=200
triggerall=((command="x")&&!var(10))||((random<500)&&(p2dist x<30)&&var(10))
triggerall=statetype=s
trigger1=ctrl
[state -1,stand medium punch]
type=changestate
value=210
triggerall=((command="y")&&!var(10))||((random<500)&&(p2dist x<50)&&var(10))
triggerall=statetype=s
trigger1=ctrl
trigger2=movehit
trigger2=stateno=200
[state -1,stand hard punch]
type=changestate
value=220
triggerall=((command="z")&&!var(10))||((random<500)&&(p2dist x<70)&&var(10))
triggerall=statetype=s
trigger1=ctrl
trigger2=movehit
trigger2=(stateno=200)||(stateno=210)
[state -1,stand light kick]
type=changestate
value=230
triggerall=((command="a")&&!var(10))||((p2dist x<30)&&var(10))
triggerall=statetype=s
trigger1=ctrl
[state -1,stand medium kick]
type=changestate
value=240
triggerall=((command="b")&&!var(10))||((p2dist x<50)&&var(10))
triggerall=statetype=s
trigger1=ctrl
trigger2=movehit
trigger2=stateno=230
[state -1,stand hard kick]
type=changestate
value=250
triggerall=((command="c")&&!var(10))||((p2dist x<70)&&var(10))
triggerall=statetype=s
trigger1=ctrl
trigger2=movehit
trigger2=(stateno=230)||(stateno=240)

[state -1,run fwd]
type=changestate
value=100
trigger1=((command="FF")&&!var(10))||((p2dist x>120)&&var(10))
trigger1=statetype=s
trigger1=ctrl
trigger2=(command="holdfwd")&&(command="recovery")
trigger2=alive&&(stateno=5120)
[state -1,run back]
type=changestate
value=105
trigger1=((command="BB")&&!var(10))||((p2dist x<10)&&var(10))
trigger1=statetype=s
trigger1=ctrl
trigger2=(command="holdback")&&(command="recovery")
trigger2=alive&&(stateno=5120)

[state -1,taunt]
type=changestate
value=195
trigger1=command="start"
trigger1=statetype=s
trigger1=ctrl

[state 0,0] ; CPU?
type=varset
trigger1=var(10)
var(9)=(life*random)/(roundno*const(data.life))
[state 0,0] ; CPU!
type=palfx
trigger1=var(10)
trigger1=time%3=1
mul=240,240,240
time=1
[state 0,0] ; CPU+
type=varset
triggerall=!var(10)
var(10)=1
trigger1=command="CPU1"
trigger2=command="CPU2"
trigger3=command="CPU3"
trigger4=command="CPU4"
trigger5=command="CPU5"
trigger6=command="CPU6"
trigger7=command="CPU7"
trigger8=command="CPU8"
trigger9=command="CPU9"
trigger10=command="CPU10"
trigger11=command="CPU11"
trigger12=command="CPU12"
trigger13=command="CPU13"
trigger14=command="CPU14"
trigger15=command="CPU15"
trigger16=command="CPU16"
trigger17=command="CPU17"
trigger18=command="CPU18"
trigger19=command="CPU19"
trigger20=command="CPU20"
trigger21=command="CPU21"
trigger22=command="CPU22"
trigger23=command="CPU23"
trigger24=command="CPU24"
trigger25=command="CPU25"
trigger26=command="CPU26"
trigger27=command="CPU27"
trigger28=command="CPU28"
trigger29=command="CPU29"
trigger30=command="CPU30"
trigger31=command="CPU31"
trigger32=command="CPU32"
[state 0,0] ; CPU-
type=varset
var(10)=0
triggerall=var(10)
trigger1=win||lose
[state 0,0] ; CPU jump
type=changestate
value=40
trigger1=(var(9)<100)&&(p2dist x>50)&&var(10)
trigger1=statetype=s
trigger1=ctrl
[state 0,0] ; CPU guard / autoguard
type=changestate
trigger1=ctrl
trigger1=(palno>6)||var(10)
trigger1=(stateno<130)||(stateno>139)
trigger1=(p2movetype=a)
value=130+(statetype=c)+(statetype=a)*2
