;-| Super Motions |--------------------------------------------------------
[Command]
name = "qcfqcf_s"
command = DF, F, D, DF, F, s
time = 25
[Command]
name = "qcfqcf_a"
command = ~D, DF, F, D, DF, a
time = 25
[Command]
name = "qcfqcf_b"
command = ~D, DF, F, D, DF, b
time = 25
[Command]
name = "qcfqcf_c"
command = ~D, DF, F, D, DF, c
time = 25
[Command]
name = "qcfqcf_x"
command = ~D, DF, F, D, DF, F, x
time = 25
[Command]
name = "qcfqcf_y"
command = ~D, DF, F, D, DF, F, y
time = 25
[Command]
name = "qcfqcf_z"
command = ~D, DF, F, D, DF, F, z
time = 25

; alternate versions for 2-in-1s
[Command]
name = "qcfqcfr_s"
command = ~D, DF, F, D, DF, F, ~s
time = 45
[Command]
name = "qcfqcfr_a"
command = ~D, DF, F, D, DF, ~a
time = 45
[Command]
name = "qcfqcfr_b"
command = ~D, DF, F, D, DF, ~b
time = 45
[Command]
name = "qcfqcfr_c"
command = ~D, DF, F, D, DF, ~c
time = 45
[Command]
name = "qcfqcfr_x"
command = ~D, DF, F, D, DF, F, ~x
time = 45
[Command]
name = "qcfqcfr_y"
command = ~D, DF, F, D, DF, F, ~y
time = 45
[Command]
name = "qcfqcfr_z"
command = ~D, DF, F, D, DF, F, ~z
time = 45

[Command]
name = "qcbqcb_s"
command = ~D, DB, B, D, DB, B, s
time = 25
[Command]
name = "qcbqcb_a"
command = ~D, DB, B, D, DB, B, a
time = 25
[Command]
name = "qcbqcb_b"
command = ~D, DB, B, D, DB, B, b
time = 25
[Command]
name = "qcbqcb_c"
command = ~D, DB, B, D, DB, B, c
time = 25
[Command]
name = "qcbqcb_x"
command = ~D, DB, B, D, DB, B, x
time = 25
[Command]
name = "qcbqcb_y"
command = ~D, DB, B, D, DB, B, y
time = 25
[Command]
name = "qcbqcb_z"
command = ~D, DB, B, D, DB, B, z
time = 25

; alternate versions for 2-in-1s
[Command]
name = "qcbqcbr_s"
command = ~D, DB, B, D, DB, B, ~s
time = 40
[Command]
name = "qcbqcbr_a"
command = ~D, DB, B, D, DB, B, ~a
time = 40
[Command]
name = "qcbqcbr_b"
command = ~D, DB, B, D, DB, B, ~b
time = 40
[Command]
name = "qcbqcbr_c"
command = ~D, DB, B, D, DB, B, ~c
time = 40
[Command]
name = "qcbqcbr_x"
command = ~D, DB, B, D, DB, B, ~x
time = 40
[Command]
name = "qcbqcbr_y"
command = ~D, DB, B, D, DB, B, ~y
time = 40
[Command]
name = "qcbqcbr_z"
command = ~D, DB, B, D, DB, B, ~z
time = 40

[Command]
name = "junkokusatsu"
command = x, x, F, a, z
time = 45
[Command]
name = "shunbokusatsu"
command = x, x, F, a, s
time = 45
[Command]
name = "junkokusa"
command = x, x, F, a
time = 25
[Command]
name = "otokomichi"
command = z, a, B, x, x
time = 45

[Command]
name = "kataki"
command = ~D, B, D, F, s
time = 25

;-| Special Motions |------------------------------------------------------

[Command]
name = "hcb_ps"
command = ~F, DF, D, DB, B, x
time = 20
[Command]
name = "hcb_ps"
command = ~F, DF, D, DB, B, y
time = 20
[Command]
name = "hcb_ps"
command = ~F, DF, D, DB, B, z
time = 20
[Command]
name = "hcb_ps"
command = ~F, DF, D, DB, B, s
time = 20

[Command]
name = "dragon_x"
command = ~F, D, DF, x
[Command]
name = "dragon_y"
command = ~F, D, DF, y
[Command]
name = "dragon_z"
command = ~F, D, DF, z

[Command]
name = "dragonr_x"
command = ~F, D, DF, ~x
time = 20
[Command]
name = "dragonr_y"
command = ~F, D, DF, ~y
time = 20
[Command]
name = "dragonr_z"
command = ~F, D, DF,  ~z
time = 20

[Command]
name = "tigerback_a"
command = ~D, DB, UB, a
[Command]
name = "tigerback_b"
command = ~D, DB, UB, b
[Command]
name = "tigerback_c"
command = ~D, DB, UB, c
[Command]
name = "tigerback_s"
command = ~D, DB, UB, s

;[Command]
;name = qcbup_a
;command = ~D, DB, B, $U, a
;[Command]
;name = qcbup_b
;command = ~D, DB, B, $U, b
;[Command]
;name = qcbup_c
;command = ~D, DB, B, $U, c

[Command]
name = "qcb_a"
command = ~D, DB, B, a
[Command]
name = "qcb_b"
command = ~D, DB, B, b
[Command]
name = "qcb_c"
command = ~D, DB, B, c
;[Command]
;name = qcb_x
;command = ~D, DB, B, x
;[Command]
;name = qcb_y
;command = ~D, DB, B, y
;[Command]
;name = qcb_z
;command = ~D, DB, B, z
[Command]
name = "qcb_s"
command = ~D, DB, B, s

; secondary versions for 2-in-1s
[Command]
name = "qcbr_a"
command = ~D, DB, B, ~a
time = 20
[Command]
name = "qcbr_b"
command = ~D, DB, B, ~b
time = 20
[Command]
name = "qcbr_c"
command = ~D, DB, B, ~c
time = 20
;[Command]
;name = qcbr_x
;command = ~D, DB, B, ~x
;time = 20
;[Command]
;name = qcbr_y
;command = ~D, DB, B, ~y
;time = 20
;[Command]
;name = qcbr_z
;command = ~D, DB, B, ~z
;time = 20
;[Command]
;name = qcbr_s
;command = ~D, DB, B, ~s
;time = 20

[Command]
name = "qcf_a"
command = ~D, DF, F, a
[Command]
name = "qcf_b"
command = ~D, DF, F, b
[Command]
name = "qcf_c"
command = ~D, DF, F, c
[Command]
name = "qcf_x"
command = ~D, DF, F, x
[Command]
name = "qcf_y"
command = ~D, DF, F, y
[Command]
name = "qcf_z"
command = ~D, DF, F, z
[Command]
name = "qcf_s"
command = ~D, DF, F, s

[Command]
name = "qcf_xy"
command = ~D,DF,F, x+y
[Command]
name = "qcf_yz"
command = ~D,DF,F, y+z
[Command]
name = "qcf_xz"
command = ~D,DF,F, x+z

; secondary versions for 2-in-1s
[Command]
name = "qcfr_a"
command = ~D, DF, F, ~a
time = 20
[Command]
name = "qcfr_b"
command = ~D, DF, F, ~b
time = 20
[Command]
name = "qcfr_c"
command = ~D, DF, F, ~c
time = 20
[Command]
name = "qcfr_x"
command = ~D, DF, F, ~x
time = 20
[Command]
name = "qcfr_y"
command = ~D, DF, F, ~y
time = 20
[Command]
name = "qcfr_z"
command = ~D, DF, F, ~z
time = 20
;[Command]
;name = qcfr_s
;command = ~D, DF, F, ~s
;time = 20

;-| Double Tap |-----------------------------------------------------------
[Command]
name = "FF_s"
command = F,F,s
time = 18

[Command]
name = "FF"
command = F, F
time = 10

;[Command]
;name = BB
;command = B, B
;time = 10

;-| 2/3 Button Combination |-----------------------------------------------
[Command]
name = "recovery" ;Required (do not remove)
command = x+y
time = 1
[Command]
name = "recovery" ;Extra recovery commands (optional)
command = y+z
time = 1
[Command]
name = "recovery" ;Extra recovery commands (optional)
command = x+z
time = 1

;-| Dir + Button |---------------------------------------------------------
[Command]
name = "df_a"
command = /DF,a
time = 1
[Command]
name = "df_b"
command = /DF,b
time = 1
[Command]
name = "df_c"
command = /DF,c
time = 1
[Command]
name = "df_x"
command = /DF,x
time = 1
[Command]
name = "df_y"
command = /DF,y
time = 1
[Command]
name = "df_z"
command = /DF,z
time = 1

[Command]
name = "db_a"
command = /DB,a
time = 1
[Command]
name = "db_b"
command = /DB,b
time = 1
[Command]
name = "db_c"
command = /DB,c
time = 1
[Command]
name = "db_x"
command = /DB,x
time = 1
[Command]
name = "db_y"
command = /DB,y
time = 1
[Command]
name = "db_z"
command = /DB,z
time = 1

[Command]
name = "dfwd_2p"
command = /DF, x+y
time = 1
[Command]
name = "dfwd_2p"
command = /DF, y+z
time = 1
[Command]
name = "dfwd_2p"
command = /DF, x+z
time = 1

[Command]
name = "fwd_2p"
command = /F, x+y
time = 1
[Command]
name = "fwd_2p"
command = /F, y+z
time = 1
[Command]
name = "fwd_2p"
command = /F, x+z
time = 1

[Command]
name = "dfwd_2k"
command = /DF, a+b
time = 1
[Command]
name = "dfwd_2k"
command = /DF, b+c
time = 1
[Command]
name = "dfwd_2k"
command = /DF, a+c
time = 1

[Command]
name = "fwd_2k"
command = /F, a+b
time = 1
[Command]
name = "fwd_2k"
command = /F, b+c
time = 1
[Command]
name = "fwd_2k"
command = /F, a+c
time = 1

[Command]
name = "release_x"
command = ~x
time = 1
[Command]
name = "release_y"
command = ~y
time = 1
[Command]
name = "release_z"
command = ~z
time = 1

[Command]
name = "back_xy"
command = /B, x+y
time = 1
[Command]
name = "back_yz"
command = /B, y+z
time = 1
[Command]
name = "back_xz"
command = /B, x+z
time = 1

[Command]
name = "back_2k"
command = /B, a+b
time = 1
[Command]
name = "back_2k"
command = /B, b+c
time = 1
[Command]
name = "back_2k"
command = /B, a+c
time = 1

[Command]
name = "xyz"
command = x+y+z
time = 1

;-| Single Button |---------------------------------------------------------
[Command]
name = "a"
command = a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "s"
command = s
time = 1

[Command]
name = "anybutton"
command = x
time = 1
[Command]
name = "anybutton"
command = y
time = 1
[Command]
name = "anybutton"
command = z
time = 1
[Command]
name = "anybutton"
command = a
time = 1
[Command]
name = "anybutton"
command = b
time = 1
[Command]
name = "anybutton"
command = c
time = 1
[Command]
name = "anybutton"
command = s
time = 1

;-| Hold Button |-----------------------------------------------------------
[Command]
name = "hold_x"
command = /x
time = 1

[Command]
name = "hold_y"
command = /y
time = 1

[Command]
name = "hold_z"
command = /z
time = 1

[Command]
name = "hold_a"
command = /a
time = 1

[Command]
name = "hold_b"
command = /b
time = 1

[Command]
name = "hold_c"
command = /c
time = 1

[Command]
name = "hold_s"
command = /s
time = 1

;-| Hold Dir |--------------------------------------------------------------
[Command]
name = "holdfwd"
command = /$F
time = 1

[Command]
name = "tapfwd"
command = $F
time = 1
[Command]
name = "releasefwd"
command = ~F
time = 1

[Command]
name = "straightfwd"
command = /F
time = 1

[Command]
name = "holdback"
command = /$B
time = 1

[Command]
name = "tapback"
command = $B
time = 1
[Command]
name = "releaseback"
command = ~B
time = 1

[Command]
name = "holdup"
command = /$U
time = 1

[Command]
name = "holddown"
command = /$D
time = 1

[Command]
name = "straightdown"
command = /D
time = 1

[Command]
name = "holdnotdown"
command = /$U
time = 1
[Command]
name = "holdnotdown"
command = /F
time = 1
[Command]
name = "holdnotdown"
command = /B
time = 1

;---------------------------------------------------------------------------
; Commands
[Statedef -1]

;===========================================================================
; supers

; Kataki
[State -1]
type = ChangeState
value = 3300
triggerall = command = "kataki"
triggerall = !var(2)
triggerall = statetype != A
triggerall = power >= 3000
trigger1 = ctrl

; Jun Kokusatsu
[State -1]
type = ChangeState
value = 3200
triggerall = command = "junkokusatsu"
triggerall = !var(2)
triggerall = power >= 3000
triggerall = statetype != A 
trigger1 = stateno = 230
trigger2 = (stateno = 200) && ifelse(P2BodyDist X <= 30,movecontact,1)
trigger3 = ctrl

; Shun Bokusatsu
[State -1]
type = ChangeState
value = 3250
triggerall = command = "shunbokusatsu"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A 
triggerall = life < 100
trigger1 = stateno = 230
trigger2 = (stateno = 200) && ifelse(P2BodyDist X <= 30,movecontact,1)
trigger3 = ctrl

; Otoko Michi
[State -1]
type = ChangeState
value = 3400
triggerall = command = "otokomichi"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = life > 1
trigger1 = stateno = [200,450]
trigger2 = stateno = 250
trigger3 = stateno = 200
trigger4 = stateno = 230
trigger5 = stateno = 195 
trigger5 = movecontact
trigger6 = stateno = [800,802]
trigger6 = movecontact
trigger7 = ctrl

; Chouhatsu Densetsu
[State -1]
type = ChangeState
value = 3000
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = command = "qcfqcf_s"
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = command = "qcfqcfr_s"
trigger2 = stateno = 195 || stateno = 802
trigger2 = movecontact

; Kouryuu Rekka (Light)
[State -1]
type = ChangeState
value = 3010
triggerall = command = "qcfqcf_a"
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = stateno = [200,240]
trigger2 = stateno!= 210 && stateno!=220
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno!=420 
trigger3 = movecontact

; Kouryuu Rekka (Light)
[State -1]
type = ChangeState
value = 3010
triggerall = command = "qcfqcfr_a"
triggerall = movecontact
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = stateno = [200,240]
trigger1 = stateno != 210
trigger1 = stateno != 220
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; Kouryuu Rekka (Light/Med)
[State -1]
type = ChangeState
value = ifelse(power<2000,3010,3020)
triggerall = command = "qcfqcf_b"
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = stateno = [200,240] ;ARRR1 added
trigger2 = stateno != 210
trigger2 = stateno != 220
trigger2 = movecontact
trigger3 = stateno = [400,450] ;ARRR1 added
trigger3 = stateno != 420
trigger3 = movecontact

; Kouryuu Rekka (Light/Med)
[State -1]
type = ChangeState
value = ifelse(power<2000,3010,3020)
triggerall = command = "qcfqcfr_b"
triggerall = movecontact
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = stateno = [200,240] ;ARRR1 added
trigger1 = stateno != 210
trigger1 = stateno != 220
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; Kouryuu Rekka (Light/Med/Hard)
[State -1]
type = ChangeState
value = 3010 + 10*((power>=2000) + (power>=3000))
triggerall = command = "qcfqcf_c"
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = stateno = [200,240]
trigger2 = stateno != 210
trigger2 = stateno != 220
trigger2 = movecontact
trigger3 = stateno = [400,450] ;ARRR1 added
trigger3 = stateno != 420
trigger3 = movecontact

; Kouryuu Rekka (Light/Med/Hard)
[State -1]
type = ChangeState
value = 3010 + 10*((power>=2000) + (power >= 3000))
triggerall = command = "qcfqcfr_c"
triggerall = movecontact
triggerall = power >= 1000
triggerall = !var(2)
trigger1 = stateno = [200,240] ;ARRR1 added
trigger1 = stateno != 210
trigger1 = stateno != 220
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; Hisshou Buraiken (light)
[State -1]
type = ChangeState
value = 3040
triggerall = command = "qcbqcb_a"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; Hisshou Buraiken (light)
[State -1]
type = ChangeState
value = 3040
triggerall = command = "qcbqcbr_a"
triggerall = movecontact
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; Hisshou Buraiken (light/med)
[State -1]
type = ChangeState
value = ifelse(power<2000,3040,3050)
triggerall = command = "qcbqcb_b"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; Hisshou Buraiken (light/med)
[State -1]
type = ChangeState
value = ifelse(power<2000,3040,3050)
triggerall = command = "qcbqcbr_b"
triggerall = movecontact
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; Hisshou Buraiken (light/med/hard)
[State -1]
type = ChangeState
value = 3040 + 10*((power>=2000) + (power>=3000))
triggerall = command = "qcbqcb_c"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; Hisshou Buraiken (light/med/hard)
[State -1]
type = ChangeState
value = 3040 + 10*((power>=2000) + (power>=3000))
triggerall = command = "qcbqcbr_c"
triggerall = movecontact
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; Shinkuu Gadouken (light)
[State -1]
type = ChangeState
value = 3070
ctrl = 0
triggerall = command = "qcfqcf_x"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; Shinkuu Gadouken (light)
[State -1]
type = ChangeState
value = 3070
ctrl = 0
triggerall = command = "qcfqcfr_x"
triggerall = movecontact
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; Shinkuu Gadouken (light/med)
[State -1]
type = ChangeState
value = ifelse(power<2000,3070,3080)
ctrl = 0
triggerall = command = "qcfqcf_y"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450] ;ARRR1 added
trigger3 = stateno != 420
trigger3 = movecontact

; Shinkuu Gadouken (light/med)
[State -1]
type = ChangeState
value = ifelse(power<2000,3070,3080)
ctrl = 0
triggerall = command = "qcfqcfr_y"
triggerall = movecontact 
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; Shinkuu Gadouken (light/med/hard)
[State -1]
type = ChangeState
value = 3070+10*((power>=2000)+(power>=3000))
ctrl = 0
triggerall = command = "qcfqcf_z"
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; Shinkuu Gadouken (light/med/hard)
[State -1]
type = ChangeState
value = 3070+10*((power>=2000)+(power>=3000))
ctrl = 0
triggerall = command = "qcfqcfr_z"
triggerall = movecontact
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; Shinkuu Gadouken (variable)
[State -1]
type = ChangeState
value = 3600
ctrl = 0
triggerall = !var(2)
triggerall = power >= 1000
triggerall = statetype != A
triggerall = command = "qcf_xy" || command = "qcf_xz" || command = "qcf_yz"
trigger1 = ctrl
trigger2 = movecontact
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger3 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420

; Chouhatsu Shinwa
[State -1]
type = ChangeState
value = 3100
triggerall = power >= 3000
triggerall = !var(2)
trigger1 = command = "qcbqcb_s"
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = command = "qcbqcbr_s"
trigger2 = movecontact
trigger2 = stateno = 802 || stateno = 195

; Jimmy!
[State -1]
type = ChangeState
value = 3450
triggerall = command = "hcb_ps" 
triggerall = !var(2)
triggerall = statetype != A
triggerall = !numhelper(3450)
triggerall = roundstate < 3
trigger1 = ctrl

; light Gadouken
[State -1]
type = ChangeState
value = 1030
triggerall = command = "qcf_x"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; light Gadouken (2-in-1)
[State -1]
type = ChangeState
value = 1030
triggerall = command = "qcfr_x"
triggerall = command != "holddown"
triggerall = movecontact
triggerall = !var(2)
triggerall = statetype != A
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; medium Gadouken
[State -1]
type = ChangeState
value = 1040
triggerall = command = "qcf_y"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; medium Gadouken
[State -1]
type = ChangeState
value = 1040
triggerall = command = "qcfr_y"
triggerall = command != "holddown"
triggerall = movecontact
triggerall = !var(2)
triggerall = statetype != A
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; strong Gadouken
[State -1]
type = ChangeState
value = 1050
triggerall = command = "qcf_z"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; strong Gadouken
[State -1]
type = ChangeState
value = 1050
triggerall = command = "qcfr_z"
triggerall = command != "holddown"
triggerall = movecontact
triggerall = !var(2)
triggerall = statetype != A
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; light Kouryuuken
[State -1]
type = ChangeState
value = 1060
triggerall = command = "dragon_x"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; light Kouryuuken
[State -1]
type = ChangeState
value = 1060
triggerall = command = "dragonr_x"
triggerall = movecontact
triggerall = !var(2)
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; med Kouryuuken
[State -1]
type = ChangeState
value = 1070
triggerall = command = "dragon_y"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; med Kouryuuken
[State -1]
type = ChangeState
value = 1070
triggerall = command = "dragonr_y"
triggerall = movecontact
triggerall = !var(2)
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; heavy Kouryuuken
[State -1]
type = ChangeState
value = 1080
triggerall = command = "dragon_z"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; heavy Kouryuuken
[State -1]
type = ChangeState
value = 1080
triggerall = command = "dragonr_z"
triggerall = movecontact
triggerall = !var(2)
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; Saikyou Zenten Hissatsu Waza
[State -1]
type = ChangeState
value = 2100
triggerall = command = "FF_s"
triggerall = !var(2)
triggerall = statetype = S
trigger1 = ctrl
trigger2 = stateno = 100
trigger2 = time < 4

; light Dan Kuu Kyaku
[State -1]
type = ChangeState
value = 1000
triggerall = command = "qcb_a"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450] ;ARRR1 added
trigger3 = stateno != 420
trigger3 = movecontact

; light Dan Kuu Kyaku
[State -1]
type = ChangeState
value = 1000
triggerall = command = "qcbr_a"
triggerall = command != "holddown"
triggerall = movecontact
triggerall = !var(2)
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450] ;ARRR1 added
trigger2 = stateno != 420

; light Dan Kuu Kyaku (ground backwards)
[State -1]
type = ChangeState
value = 1007
triggerall = command = "tigerback_a"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = stateno = 40
trigger2 = stateno = 43
trigger2 = statetime <= 3

; light Dan Kuu Kyaku (air, forward/backward/neutral)
[State -1]
type = ChangeState
value = 1005+(anim%3 = 2)
triggerall = command = "qcb_a"
triggerall = !var(2)
triggerall = statetype = A
trigger1 = stateno = 50
trigger1 = ctrl
trigger1 = (anim != 43) || (time > 3) ; prevent this from triggering when
				      ; someone wanted 1007 but messed up.

; medium Dan Kuu Kyaku
[State -1]
type = ChangeState
value = 1010
triggerall = command = "qcb_b"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; medium Dan Kuu Kyaku
[State -1]
type = ChangeState
value = 1010
triggerall = command = "qcbr_b"
triggerall = command != "holddown"
triggerall = movecontact
triggerall = !var(2)
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; medium Dan Kuu Kyaku (ground backwards)
[State -1]
type = ChangeState
value = 1017
triggerall = command = "tigerback_b"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = stateno = 40
trigger2 = stateno = 43
trigger2 = statetime <= 3

; medium Dan Kuu Kyaku (air, forward/backward/neutral)
[State -1]
type = ChangeState
value = 1015+(anim%3 = 2)
triggerall = command = "qcb_b"
;triggerall = command != "holdup" ; hakk
triggerall = !var(2)
triggerall = statetype = A
trigger1 = anim = [41,46]
trigger1 = ctrl
trigger1 = (anim != 43) || (time > 3) ; prevent this from triggering when
				      ; someone wanted 1017 but messed up.

; hard Dan Kuu Kyaku
[State -1]
type = ChangeState
value = 1020
triggerall = command = "qcb_c"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; hard Dan Kuu Kyaku
[State -1]
type = ChangeState
value = 1020
triggerall = command = "qcbr_c"
triggerall = command != "holddown"
triggerall = movecontact
triggerall = !var(2)
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; hard Dan Kuu Kyaku (ground backwards)
[State -1]
type = ChangeState
value = 1027
triggerall = command = "tigerback_c"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = stateno = 40
trigger2 = stateno = 43
trigger2 = statetime <= 3

; hard Dan Kuu Kyaku (air, forward/backward/neutral)
[State -1]
type = ChangeState
value = 1025+(anim%3 = 2)
triggerall = command = "qcb_c"
;triggerall = command != "holdup" ; hakk
triggerall = !var(2)
triggerall = statetype = A
trigger1 = anim = [41,46]
trigger1 = ctrl
trigger1 = (anim != 43) || (time > 3) ; prevent this from triggering when
				      ; someone wanted 1027 but messed up.

; light Premium Sign
[State -1]
type = ChangeState
value = 1100
triggerall = command = "qcf_a"
triggerall = !var(2)
triggerall = statetype != A
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; light Premium Sign
[State -1]
type = ChangeState
value = 1100
triggerall = command = "qcfr_a"
triggerall = !var(2)
triggerall = movecontact
triggerall = command != "holddown"
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; medium Premium Sign
[State -1]
type = ChangeState
value = 1110
triggerall = command = "qcf_b"
triggerall = !var(2)
triggerall = statetype != A
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; medium Premium Sign
[State -1]
type = ChangeState
value = 1110
triggerall = command = "qcfr_b"
triggerall = !var(2)
triggerall = movecontact
triggerall = command != "holddown"
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; strong Premium Sign
[State -1]
type = ChangeState
value = 1120
triggerall = command = "qcf_c"
triggerall = !var(2)
triggerall = statetype != A
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = movecontact
trigger3 = stateno = [400,450]
trigger3 = stateno != 420
trigger3 = movecontact

; strong Premium Sign
[State -1]
type = ChangeState
value = 1120
triggerall = command = "qcfr_c"
triggerall = movecontact
triggerall = !var(2)
triggerall = command != "holddown"
trigger1 = stateno = 200 || stateno = 230 || stateno = 240
trigger2 = stateno = [400,450]
trigger2 = stateno != 420

; standing Zero counter
[State -1]
type = ChangeState
value = 2000
triggerall = command = "fwd_2p" || command = "dfwd_2p"
triggerall = var(2) = 0
triggerall = power >= 1000
trigger1 = stateno = 150 && command = "fwd_2p"
trigger2 = stateno = 152

; crouching Zero counter
[State -1]
type = ChangeState
value = 2020
triggerall = command = "fwd_2k" || command = "dfwd_2k"
triggerall = !var(2)
triggerall = power >= 1000
trigger1 = stateno = 150 && command = "fwd_2k"
trigger2 = stateno = 152

;------------------------
; forward roll taunt
[State -1]
type = ChangeState
value = 800
triggerall = command = "qcf_s"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;-------------------------
; back roll taunt
[State -1]
type = ChangeState
value = 801
triggerall = command = "qcb_s"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;===========================================================================
;---------------------------------------------------------------------------
;RunFwd
[State -1]
type = ChangeState
value = 100
triggerall = !var(2)
trigger1 = command = "FF"
trigger1 = statetype = S
trigger1 = ctrl = 1

; Saikyou Backdash
[State -1]
type = ChangeState
value = 805
triggerall = !var(2)
trigger1 = command = "tigerback_s"
trigger1 = stateno = 40

;===========================================================================
;---------------------------------------------------------------------------
; Saikyou-ryuu Bougyo
[State -1]
type = ChangeState
value = 135
triggerall = stateno = 154
triggerall = !var(2)
trigger1 = command = "xyz"
;trigger1 = command = recovery

; Otoko Michibiki
[State -1]
type = ChangeState
value = 1200
triggerall = statetype = S
triggerall = ctrl
triggerall = !var(2)
trigger1 = command = "fwd_2k"
value = 1200
ctrl = 0

; Seoi Nage
[State -1]
type = ChangeState
value = 900+2*(statetype = A)
triggerall = statetype != C
triggerall = ctrl
triggerall = !var(2)
trigger1 = command = "fwd_2p" ; || (command = "fwd_yz") || (command = "fwd_xz")

; Seoi Nage back
[State -1]
type = ChangeState
value = 901+2*(statetype = A)
triggerall = statetype != C
triggerall = ctrl
triggerall = !var(2)
trigger1 = command = "back_xy"
trigger2 = command = "back_xz"
trigger3 = command = "back_yz"

; Saikyou Jigoku Otoshi
[State -1]
type = ChangeState
value = 980
triggerall = statetype = A
triggerall = ctrl
triggerall = !var(2)
trigger1 = command = "fwd_2k"
trigger2 = command = "back_2k"

; Generic Kick Throw
[State -1]
type = ChangeState
value = 950
triggerall = statetype = S
triggerall = ctrl
triggerall = !var(2)
trigger1 = command = "back_2k"

; Chouhatsu Shinwa forward roll A
[State -1]
type = ChangeState
value = 3130
triggerall = command = "df_a"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa forward roll B
[State -1]
type = ChangeState
value = 3131
triggerall = command = "df_b"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa forward roll C
[State -1]
type = ChangeState
value = 3132
triggerall = command = "df_c"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa forward roll X
[State -1]
type = ChangeState
value = 3133
triggerall = command = "df_x"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa forward roll Y
[State -1]
type = ChangeState
value = 3134
triggerall = command = "df_y"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa forward roll Z
[State -1]
type = ChangeState
value = 3135
triggerall = command = "df_z"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa backward roll A
[State -1]
type = ChangeState
value = 3150
triggerall = command = "db_a"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa backward roll B
[State -1]
type = ChangeState
value = 3151
triggerall = command = "db_b"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa backward roll C
[State -1]
type = ChangeState
value = 3152
triggerall = command = "db_c"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa backward roll X
[State -1]
type = ChangeState
value = 3153
triggerall = command = "db_x"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa backward roll Y
[State -1]
type = ChangeState
value = 3154
triggerall = command = "db_y"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

; Chouhatsu Shinwa backward roll Z
[State -1]
type = ChangeState
value = 3155
triggerall = command = "db_z"
triggerall = var(2)
trigger1 = statetype != A
trigger1 = ctrl

;-----------------------------------

;Stand_A
[State -1]
type = ChangeState
value = 200
triggerall = command = "a"
triggerall = command != "holddown"
triggerall = !var(2)
triggerall = statetype = S
trigger1 = ctrl
trigger2 = command = "junkokusa"
trigger2 = movecontact

;Stand_A alternate
[State -1]
type = ChangeState
value = 3120
triggerall = command = "a"
triggerall = command != "holddown"
triggerall = var(2)
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand_B
[State -1]
type = ChangeState
value = 210
triggerall = command = "b"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;Stand_B
[State -1]
type = ChangeState
value = 3121
triggerall = command = "b"
triggerall = command != "holddown"
triggerall = var(2)
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand_C
[State -1]
type = ChangeState
value = 220
triggerall = command = "c"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;Stand_C alternate
[State -1]
type = ChangeState
value = 3122
triggerall = command = "c"
triggerall = command != "holddown"
triggerall = var(2)
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand_X
[State -1]
type = ChangeState
value = 230
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;Stand_X alternate
[State -1]
type = ChangeState
value = 3123
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = var(2)
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand_Y
[State -1]
type = ChangeState
value = 240
triggerall = command = "y"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;Stand_Y alternate
[State -1]
type = ChangeState
value = 3124
triggerall = command = "y"
triggerall = command != "holddown"
triggerall = var(2)
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand_Z
[State -1]
type = ChangeState
value = 250
triggerall = command = "z"
triggerall = command != "holddown"
triggerall = !var(2)
trigger1 = statetype = S
trigger1 = ctrl

;Stand_Z alternate
[State -1]
type = ChangeState
value = 3125
triggerall = command = "z"
triggerall = command != "holddown"
triggerall = var(2)
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouch_A
[State -1]
type = ChangeState
value = 400
triggerall = command = "a"
triggerall = command = "holddown"
triggerall = !var(2)
trigger1 = statetype = C
trigger1 = ctrl

;Crouch_A
[State -1]
type = ChangeState
value = 3140
triggerall = command = "a"
triggerall = command = "holddown"
triggerall = var(2)
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouch_B
[State -1]
type = ChangeState
value = 410
triggerall = command = "b"
triggerall = command = "holddown"
triggerall = !var(2)
trigger1 = statetype = C
trigger1 = ctrl

;Crouch_B alternate
[State -1]
type = ChangeState
value = 3141
triggerall = command = "b"
triggerall = command = "holddown"
triggerall = var(2)
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouch_C
[State -1]
type = ChangeState
value = 420
triggerall = command = "c"
triggerall = command = "holddown"
triggerall = !var(2)
trigger1 = statetype = C
trigger1 = ctrl

;Crouch_C alternate
[State -1]
type = ChangeState
value = 3142
triggerall = command = "c"
triggerall = command = "holddown"
triggerall = var(2)
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouch_X
[State -1]
type = ChangeState
value = 430
triggerall = command = "x"
triggerall = command = "holddown"
triggerall = !var(2)
trigger1 = statetype = C
trigger1 = ctrl

;Crouch_X alternate
[State -1]
type = ChangeState
value = 3143
triggerall = command = "x"
triggerall = command = "holddown"
triggerall = var(2)
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouch_Y
[State -1]
type = ChangeState
value = 440
triggerall = command = "y"
triggerall = command = "holddown"
triggerall = !var(2)
trigger1 = statetype = C
trigger1 = ctrl

;Crouch_Y alternate
[State -1]
type = ChangeState
value = 3144
triggerall = command = "y"
triggerall = command = "holddown"
triggerall = var(2)
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouch_Z
[State -1]
type = ChangeState
value = 450
triggerall = command = "z"
triggerall = command = "holddown"
triggerall = !var(2)
trigger1 = statetype = C
trigger1 = ctrl

;Crouch_Z alternate
[State -1]
type = ChangeState
value = 3145
triggerall = command = "z"
triggerall = command = "holddown"
triggerall = var(2)
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Jump_C
[State -1]
type = ChangeState
value = 620
triggerall = command = "c"
triggerall = !var(2)
trigger1 = statetype = A
trigger1 = ctrl

;Jump_C
[State -1]
type = ChangeState
value = 3162
triggerall = command = "c"
triggerall = var(2)
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;Jump_A
[State -1]
type = ChangeState
value = 600
triggerall = command = "a"
triggerall = !var(2)
trigger1 = statetype = A
trigger1 = ctrl

;Jump_A alternate
[State -1]
type = ChangeState
value = 3160
triggerall = command = "a"
triggerall = var(2)
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;Jump_B
[State -1]
type = ChangeState
value = 610
triggerall = !var(2)
trigger1 = command = "b"
trigger1 = statetype = A
trigger1 = ctrl

;Jump_B alternate
[State -1]
type = ChangeState
value = 3161
triggerall = var(2)
trigger1 = command = "b"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;Jump_X
[State -1]
type = ChangeState
value = 630
triggerall = !var(2)
triggerall = command = "x"
trigger1 = statetype = A
trigger1 = ctrl

;Jump_X alternate
[State -1]
type = ChangeState
value = 3163
triggerall = var(2)
triggerall = command = "x"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;Jump_Y
[State -1]
type = ChangeState
value = 640
triggerall = !var(2)
triggerall = command = "y"
trigger1 = statetype = A
trigger1 = ctrl

;Jump_Y alternate
[State -1]
type = ChangeState
value = 3164
triggerall = var(2)
triggerall = command = "y"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;Jump_Z
[State -1]
type = ChangeState
value = 650
triggerall = !var(2)
triggerall = command = "z"
trigger1 = statetype = A
trigger1 = ctrl

;Jump_Z alternate
[State -1]
type = ChangeState
value = 3165
triggerall = var(2)
triggerall = command = "z"
trigger1 = statetype = A
trigger1 = ctrl

;-----------
;Jump_S
[State -1]
type = ChangeState
value = 803
triggerall = !var(2)
triggerall = command = "s"
trigger1 = statetype = A
trigger1 = Vel Y < 0
trigger1 = ctrl

;Jump_S alternate
[State -1]
type = ChangeState
value = 3197
triggerall = var(2)
triggerall = command = "s"
trigger1 = statetype = A
trigger1 = ctrl

;-----------------------
; Standing taunt
[State -1]
type = ChangeState
value = 195
triggerall = !var(2)
triggerall = command = "s"
trigger1 = statetype = S
trigger1 = ctrl

; Standing taunt alternate
[State -1]
type = ChangeState
value = 3195
triggerall = var(2)
triggerall = command = "s"
trigger1 = statetype = S
trigger1 = ctrl

;-----------------------
; Crouching Taunt
[State -1]
type = ChangeState
value = 802
triggerall = !var(2)
triggerall = command = "s"
trigger1 = statetype = C
trigger1 = ctrl

; Crouching taunt alternate
[State -1]
type = ChangeState
value = 3196
triggerall = var(2)
triggerall = command = "s"
trigger1 = statetype = C
trigger1 = ctrl


